version: "3"
services:

  finbotdb:
    image: "postgres:12"
    container_name: finbotdb
    restart: always
    shm_size: 256MB
    environment:
        POSTGRES_PORT: 5432
        POSTGRES_DB: finbot
        POSTGRES_USER: finbot
        POSTGRES_PASSWORD: finbot
    ports:
      - "5432:5432"
    volumes:
      - .finbotdb:/var/lib/postgresql/data

  finbotwsrv:
    build:
      context: .
      dockerfile: finbotwsrv.Dockerfile
    container_name: finbotwsrv
    working_dir: /finbot
    command: "make run-finbotwsrv-dev"
    ports:
      - "5001:5001"
    volumes:
      - .:/finbot

  snapwsrv:
    build:
      context: .
      dockerfile: snapwsrv.Dockerfile
    container_name: snapwsrv
    depends_on: 
      - finbotdb
    working_dir: /finbot
    command: sh -c "/usr/bin/wait && make run-snapwsrv-dev"
    ports:
      - "5000:5000"
    volumes:
      - .:/finbot
    environment:
      WAIT_HOSTS: finbotdb:5432, finbotwsrv:5001
      FINBOT_FINBOTWSRV_ENDPOINT: "http://finbotwsrv:5001"
      FINBOT_DB_HOSTNAME: finbotdb

  histwsrv:
    build:
      context: .
      dockerfile: histwsrv.Dockerfile
    container_name: histwsrv
    depends_on: 
      - finbotdb
    working_dir: /finbot
    command: sh -c "/usr/bin/wait && make run-histwsrv-dev"
    ports:
      - "5002:5002"
    volumes:
      - .:/finbot
    environment:
      WAIT_HOSTS: finbotdb:5432
      FINBOT_DB_HOSTNAME: finbotdb

  schedsrv:
    build:
      context: .
      dockerfile: schedsrv.Dockerfile
    container_name: schedsrv
    depends_on: 
      - snapwsrv
      - histwsrv
    working_dir: /finbot
    command: sh -c "/usr/bin/wait && make run-schedsrv-dev"
    volumes:
      - .:/finbot
    environment:
      WAIT_HOSTS: histwsrv:5002, snapwsrv:5000
      FINBOT_DB_HOSTNAME: finbotdb
      FINBOT_SNAPWSRV_ENDPOINT: "http://snapwsrv:5000"
      FINBOT_HISTWSRV_ENDPOINT: "http://histwsrv:5002"

  appwsrv:
    build:
      context: .
      dockerfile: appwsrv.Dockerfile
    container_name: appwsrv
    depends_on: 
      - finbotdb
    working_dir: /finbot
    command: sh -c "/usr/bin/wait && make run-appwsrv-dev"
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      WAIT_HOSTS: finbotdb:5432
      FINBOT_DB_HOSTNAME: finbotdb

volumes:
    .finbotdb:
    .:
